let respostaUm = prompt("Qual seu nome?")
let respostaDois = prompt("Qual sua idade?")
let respostaTres = prompt("Qual seu user no instagram?")
let respostaQuatro = prompt("Qual seu é seu user no twitter?")
let respostaCinco = prompt("Nome do seu canal no youtube:")
console.log("1.Qual seu nome? ")
console.log("Resposta: "+ respostaUm)
console.log("2.Qual sua idade?")
console.log("Resposta: " + respostaDois)
console.log("3.Qual seu user no instagram?")
console.log("Resposta: " + respostaTres)
console.log("4.Qual seu é seu user no twitter?")
console.log("Resposta: " + respostaQuatro)
console.log("5.Nome do seu canal no youtube:")
console.log("Resposta: " + respostaCinco)